// Code generated by ent, DO NOT EDIT.

//go:build tools
// +build tools

// Package internal holds a loadable version of the latest schema.
package internal

const Schema = `{"Schema":"github.com/wtkeqrf0/TestGRPC/ent/schema","Package":"github.com/wtkeqrf0/TestGRPC/ent","Schemas":[{"name":"Author","config":{"Table":""},"edges":[{"name":"books","type":"Book","ref_name":"authors","inverse":true}],"fields":[{"name":"first_name","type":{"Type":7,"Ident":"","PkgPath":"","PkgName":"","Nillable":false,"RType":null},"validators":1,"position":{"Index":0,"MixedIn":false,"MixinIndex":0}},{"name":"surname","type":{"Type":7,"Ident":"","PkgPath":"","PkgName":"","Nillable":false,"RType":null},"validators":1,"position":{"Index":1,"MixedIn":false,"MixinIndex":0}},{"name":"patronymic","type":{"Type":7,"Ident":"","PkgPath":"","PkgName":"","Nillable":false,"RType":null},"nillable":true,"optional":true,"validators":1,"position":{"Index":2,"MixedIn":false,"MixinIndex":0}}]},{"name":"Book","config":{"Table":""},"edges":[{"name":"authors","type":"Author"}],"fields":[{"name":"id","type":{"Type":7,"Ident":"","PkgPath":"","PkgName":"","Nillable":false,"RType":null},"validators":1,"storage_key":"title","position":{"Index":0,"MixedIn":false,"MixinIndex":0}}]}],"Features":["intercept","sql/upsert","schema/snapshot"]}`
