// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/wtkeqrf0/TestGRPC/ent/author"
	"github.com/wtkeqrf0/TestGRPC/ent/book"
)

// AuthorCreate is the builder for creating a Author entity.
type AuthorCreate struct {
	config
	mutation *AuthorMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetFirstName sets the "first_name" field.
func (ac *AuthorCreate) SetFirstName(s string) *AuthorCreate {
	ac.mutation.SetFirstName(s)
	return ac
}

// SetSurname sets the "surname" field.
func (ac *AuthorCreate) SetSurname(s string) *AuthorCreate {
	ac.mutation.SetSurname(s)
	return ac
}

// SetPatronymic sets the "patronymic" field.
func (ac *AuthorCreate) SetPatronymic(s string) *AuthorCreate {
	ac.mutation.SetPatronymic(s)
	return ac
}

// SetNillablePatronymic sets the "patronymic" field if the given value is not nil.
func (ac *AuthorCreate) SetNillablePatronymic(s *string) *AuthorCreate {
	if s != nil {
		ac.SetPatronymic(*s)
	}
	return ac
}

// AddBookIDs adds the "books" edge to the Book entity by IDs.
func (ac *AuthorCreate) AddBookIDs(ids ...string) *AuthorCreate {
	ac.mutation.AddBookIDs(ids...)
	return ac
}

// AddBooks adds the "books" edges to the Book entity.
func (ac *AuthorCreate) AddBooks(b ...*Book) *AuthorCreate {
	ids := make([]string, len(b))
	for i := range b {
		ids[i] = b[i].ID
	}
	return ac.AddBookIDs(ids...)
}

// Mutation returns the AuthorMutation object of the builder.
func (ac *AuthorCreate) Mutation() *AuthorMutation {
	return ac.mutation
}

// Save creates the Author in the database.
func (ac *AuthorCreate) Save(ctx context.Context) (*Author, error) {
	return withHooks(ctx, ac.sqlSave, ac.mutation, ac.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (ac *AuthorCreate) SaveX(ctx context.Context) *Author {
	v, err := ac.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ac *AuthorCreate) Exec(ctx context.Context) error {
	_, err := ac.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ac *AuthorCreate) ExecX(ctx context.Context) {
	if err := ac.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ac *AuthorCreate) check() error {
	if _, ok := ac.mutation.FirstName(); !ok {
		return &ValidationError{Name: "first_name", err: errors.New(`ent: missing required field "Author.first_name"`)}
	}
	if v, ok := ac.mutation.FirstName(); ok {
		if err := author.FirstNameValidator(v); err != nil {
			return &ValidationError{Name: "first_name", err: fmt.Errorf(`ent: validator failed for field "Author.first_name": %w`, err)}
		}
	}
	if _, ok := ac.mutation.Surname(); !ok {
		return &ValidationError{Name: "surname", err: errors.New(`ent: missing required field "Author.surname"`)}
	}
	if v, ok := ac.mutation.Surname(); ok {
		if err := author.SurnameValidator(v); err != nil {
			return &ValidationError{Name: "surname", err: fmt.Errorf(`ent: validator failed for field "Author.surname": %w`, err)}
		}
	}
	if v, ok := ac.mutation.Patronymic(); ok {
		if err := author.PatronymicValidator(v); err != nil {
			return &ValidationError{Name: "patronymic", err: fmt.Errorf(`ent: validator failed for field "Author.patronymic": %w`, err)}
		}
	}
	return nil
}

func (ac *AuthorCreate) sqlSave(ctx context.Context) (*Author, error) {
	if err := ac.check(); err != nil {
		return nil, err
	}
	_node, _spec := ac.createSpec()
	if err := sqlgraph.CreateNode(ctx, ac.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	ac.mutation.id = &_node.ID
	ac.mutation.done = true
	return _node, nil
}

func (ac *AuthorCreate) createSpec() (*Author, *sqlgraph.CreateSpec) {
	var (
		_node = &Author{config: ac.config}
		_spec = sqlgraph.NewCreateSpec(author.Table, sqlgraph.NewFieldSpec(author.FieldID, field.TypeInt))
	)
	_spec.OnConflict = ac.conflict
	if value, ok := ac.mutation.FirstName(); ok {
		_spec.SetField(author.FieldFirstName, field.TypeString, value)
		_node.FirstName = value
	}
	if value, ok := ac.mutation.Surname(); ok {
		_spec.SetField(author.FieldSurname, field.TypeString, value)
		_node.Surname = value
	}
	if value, ok := ac.mutation.Patronymic(); ok {
		_spec.SetField(author.FieldPatronymic, field.TypeString, value)
		_node.Patronymic = &value
	}
	if nodes := ac.mutation.BooksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   author.BooksTable,
			Columns: author.BooksPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(book.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Author.Create().
//		SetFirstName(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AuthorUpsert) {
//			SetFirstName(v+v).
//		}).
//		Exec(ctx)
func (ac *AuthorCreate) OnConflict(opts ...sql.ConflictOption) *AuthorUpsertOne {
	ac.conflict = opts
	return &AuthorUpsertOne{
		create: ac,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Author.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (ac *AuthorCreate) OnConflictColumns(columns ...string) *AuthorUpsertOne {
	ac.conflict = append(ac.conflict, sql.ConflictColumns(columns...))
	return &AuthorUpsertOne{
		create: ac,
	}
}

type (
	// AuthorUpsertOne is the builder for "upsert"-ing
	//  one Author node.
	AuthorUpsertOne struct {
		create *AuthorCreate
	}

	// AuthorUpsert is the "OnConflict" setter.
	AuthorUpsert struct {
		*sql.UpdateSet
	}
)

// SetFirstName sets the "first_name" field.
func (u *AuthorUpsert) SetFirstName(v string) *AuthorUpsert {
	u.Set(author.FieldFirstName, v)
	return u
}

// UpdateFirstName sets the "first_name" field to the value that was provided on create.
func (u *AuthorUpsert) UpdateFirstName() *AuthorUpsert {
	u.SetExcluded(author.FieldFirstName)
	return u
}

// SetSurname sets the "surname" field.
func (u *AuthorUpsert) SetSurname(v string) *AuthorUpsert {
	u.Set(author.FieldSurname, v)
	return u
}

// UpdateSurname sets the "surname" field to the value that was provided on create.
func (u *AuthorUpsert) UpdateSurname() *AuthorUpsert {
	u.SetExcluded(author.FieldSurname)
	return u
}

// SetPatronymic sets the "patronymic" field.
func (u *AuthorUpsert) SetPatronymic(v string) *AuthorUpsert {
	u.Set(author.FieldPatronymic, v)
	return u
}

// UpdatePatronymic sets the "patronymic" field to the value that was provided on create.
func (u *AuthorUpsert) UpdatePatronymic() *AuthorUpsert {
	u.SetExcluded(author.FieldPatronymic)
	return u
}

// ClearPatronymic clears the value of the "patronymic" field.
func (u *AuthorUpsert) ClearPatronymic() *AuthorUpsert {
	u.SetNull(author.FieldPatronymic)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.Author.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *AuthorUpsertOne) UpdateNewValues() *AuthorUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Author.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *AuthorUpsertOne) Ignore() *AuthorUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AuthorUpsertOne) DoNothing() *AuthorUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AuthorCreate.OnConflict
// documentation for more info.
func (u *AuthorUpsertOne) Update(set func(*AuthorUpsert)) *AuthorUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AuthorUpsert{UpdateSet: update})
	}))
	return u
}

// SetFirstName sets the "first_name" field.
func (u *AuthorUpsertOne) SetFirstName(v string) *AuthorUpsertOne {
	return u.Update(func(s *AuthorUpsert) {
		s.SetFirstName(v)
	})
}

// UpdateFirstName sets the "first_name" field to the value that was provided on create.
func (u *AuthorUpsertOne) UpdateFirstName() *AuthorUpsertOne {
	return u.Update(func(s *AuthorUpsert) {
		s.UpdateFirstName()
	})
}

// SetSurname sets the "surname" field.
func (u *AuthorUpsertOne) SetSurname(v string) *AuthorUpsertOne {
	return u.Update(func(s *AuthorUpsert) {
		s.SetSurname(v)
	})
}

// UpdateSurname sets the "surname" field to the value that was provided on create.
func (u *AuthorUpsertOne) UpdateSurname() *AuthorUpsertOne {
	return u.Update(func(s *AuthorUpsert) {
		s.UpdateSurname()
	})
}

// SetPatronymic sets the "patronymic" field.
func (u *AuthorUpsertOne) SetPatronymic(v string) *AuthorUpsertOne {
	return u.Update(func(s *AuthorUpsert) {
		s.SetPatronymic(v)
	})
}

// UpdatePatronymic sets the "patronymic" field to the value that was provided on create.
func (u *AuthorUpsertOne) UpdatePatronymic() *AuthorUpsertOne {
	return u.Update(func(s *AuthorUpsert) {
		s.UpdatePatronymic()
	})
}

// ClearPatronymic clears the value of the "patronymic" field.
func (u *AuthorUpsertOne) ClearPatronymic() *AuthorUpsertOne {
	return u.Update(func(s *AuthorUpsert) {
		s.ClearPatronymic()
	})
}

// Exec executes the query.
func (u *AuthorUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AuthorCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AuthorUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *AuthorUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *AuthorUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// AuthorCreateBulk is the builder for creating many Author entities in bulk.
type AuthorCreateBulk struct {
	config
	builders []*AuthorCreate
	conflict []sql.ConflictOption
}

// Save creates the Author entities in the database.
func (acb *AuthorCreateBulk) Save(ctx context.Context) ([]*Author, error) {
	specs := make([]*sqlgraph.CreateSpec, len(acb.builders))
	nodes := make([]*Author, len(acb.builders))
	mutators := make([]Mutator, len(acb.builders))
	for i := range acb.builders {
		func(i int, root context.Context) {
			builder := acb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AuthorMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, acb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = acb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, acb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, acb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (acb *AuthorCreateBulk) SaveX(ctx context.Context) []*Author {
	v, err := acb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (acb *AuthorCreateBulk) Exec(ctx context.Context) error {
	_, err := acb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (acb *AuthorCreateBulk) ExecX(ctx context.Context) {
	if err := acb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Author.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AuthorUpsert) {
//			SetFirstName(v+v).
//		}).
//		Exec(ctx)
func (acb *AuthorCreateBulk) OnConflict(opts ...sql.ConflictOption) *AuthorUpsertBulk {
	acb.conflict = opts
	return &AuthorUpsertBulk{
		create: acb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Author.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (acb *AuthorCreateBulk) OnConflictColumns(columns ...string) *AuthorUpsertBulk {
	acb.conflict = append(acb.conflict, sql.ConflictColumns(columns...))
	return &AuthorUpsertBulk{
		create: acb,
	}
}

// AuthorUpsertBulk is the builder for "upsert"-ing
// a bulk of Author nodes.
type AuthorUpsertBulk struct {
	create *AuthorCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Author.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *AuthorUpsertBulk) UpdateNewValues() *AuthorUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Author.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *AuthorUpsertBulk) Ignore() *AuthorUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AuthorUpsertBulk) DoNothing() *AuthorUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AuthorCreateBulk.OnConflict
// documentation for more info.
func (u *AuthorUpsertBulk) Update(set func(*AuthorUpsert)) *AuthorUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AuthorUpsert{UpdateSet: update})
	}))
	return u
}

// SetFirstName sets the "first_name" field.
func (u *AuthorUpsertBulk) SetFirstName(v string) *AuthorUpsertBulk {
	return u.Update(func(s *AuthorUpsert) {
		s.SetFirstName(v)
	})
}

// UpdateFirstName sets the "first_name" field to the value that was provided on create.
func (u *AuthorUpsertBulk) UpdateFirstName() *AuthorUpsertBulk {
	return u.Update(func(s *AuthorUpsert) {
		s.UpdateFirstName()
	})
}

// SetSurname sets the "surname" field.
func (u *AuthorUpsertBulk) SetSurname(v string) *AuthorUpsertBulk {
	return u.Update(func(s *AuthorUpsert) {
		s.SetSurname(v)
	})
}

// UpdateSurname sets the "surname" field to the value that was provided on create.
func (u *AuthorUpsertBulk) UpdateSurname() *AuthorUpsertBulk {
	return u.Update(func(s *AuthorUpsert) {
		s.UpdateSurname()
	})
}

// SetPatronymic sets the "patronymic" field.
func (u *AuthorUpsertBulk) SetPatronymic(v string) *AuthorUpsertBulk {
	return u.Update(func(s *AuthorUpsert) {
		s.SetPatronymic(v)
	})
}

// UpdatePatronymic sets the "patronymic" field to the value that was provided on create.
func (u *AuthorUpsertBulk) UpdatePatronymic() *AuthorUpsertBulk {
	return u.Update(func(s *AuthorUpsert) {
		s.UpdatePatronymic()
	})
}

// ClearPatronymic clears the value of the "patronymic" field.
func (u *AuthorUpsertBulk) ClearPatronymic() *AuthorUpsertBulk {
	return u.Update(func(s *AuthorUpsert) {
		s.ClearPatronymic()
	})
}

// Exec executes the query.
func (u *AuthorUpsertBulk) Exec(ctx context.Context) error {
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the AuthorCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AuthorCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AuthorUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
